#!/usr/bin/php

<?php

const FILE_COMPOSER_JSON = 'composer.json';
const URL_FILE_NOVA = 'https://media.reptily.ru/files/nova.tar.gz';
const DIR_NOVA = './vendor/___private';
const FILE_NOVA = 'nova.tar.gz';

$version = explode('.', PHP_VERSION) ?? [];

if (empty($version) || $version[0] < 7) {
    echo "\e[0;31mNeed PHP version >= 7.0.0 \e[0m\n";
    exit();
}

if (!file_exists(FILE_COMPOSER_JSON)) {
    echo "\e[0;31mFile " . FILE_COMPOSER_JSON . " not exists :(\e[0m\n";
    exit();
}

$composerJson = json_decode(file_get_contents(FILE_COMPOSER_JSON), false) ?? false;

if ($composerJson === false) {
    echo "\e[0;31mFile " . FILE_COMPOSER_JSON . " is bad :(\e[0m\n";
    exit();
}

$nova = "laravel/nova";
$alreadyInstallNova = (bool) ($composerJson->require->$nova ?? false);


if ($alreadyInstallNova === true) {
    echo "\e[1;33mLaravel Nova already install\e[0m\n";
    exit();
}

$composerJson->require->$nova = "*";

$repositories = $composerJson->repositories ?? [];

$repositories[] = (object) [
    "type" => "path",
    "url" => "./vendor/___private/nova",
];

$composerJson->repositories = $repositories;

echo "\e[0;32mDownloading file Laravel Nova\e[0m\n";
@mkdir(DIR_NOVA, 0755, true);
file_put_contents(DIR_NOVA . "/" . FILE_NOVA, file_get_contents(URL_FILE_NOVA));

try {
    echo "\e[0;32mExtract file Laravel Nova\e[0m\n";
    $phar = new PharData(DIR_NOVA . "/" . FILE_NOVA);
    $phar->extractTo(DIR_NOVA);
} catch (Exception $e) {
    echo "\e[1;33mExtract file error, " . DIR_NOVA . "/" . FILE_NOVA . "extract tar utils \e[0m\n";
    exec("tar -xf " . DIR_NOVA . "/" . FILE_NOVA . " -C " . DIR_NOVA);
}

echo "\e[0;32mAppend Laravel Nova in composer.json\e[0m\n";
file_put_contents(
    FILE_COMPOSER_JSON,
    json_encode($composerJson, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)
);
